// AUTO-GENERATED by scripts/fetch-businesses.mjs — do not hand-edit.
// Refreshed weekly (see the "daxi-businesses-refresh" scheduled task) from
// Google Places API (New), Nearby Search, ranked by review count within
// 1200m of Daxi Old Street. Regenerate with:
//   node --env-file=.env.local scripts/fetch-businesses.mjs

export type Business = {
  placeId: string;
  name: string;
  address: string | null;
  category: string | null;
  rating: number | null;
  reviewCount: number;
  lat: number;
  lng: number;
  distanceMeters: number;
  distanceLabel: string;
  mapsUrl: string;
};

export const businessesGeneratedAt = "2026-07-20T03:35:58.740Z";

export const businesses: Business[] = [
  {
    "placeId": "ChIJuwRV3SEYaDQRiEQnq6NCVw4",
    "name": "老阿伯現滷豆干",
    "address": "335台灣桃園市大溪區興和里中正路37號",
    "category": "vegan_restaurant",
    "rating": 4,
    "reviewCount": 10401,
    "lat": 24.8829454,
    "lng": 121.28626570000002,
    "distanceMeters": 299,
    "distanceLabel": "300m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.8829454,121.28626570000002&destination_place_id=ChIJuwRV3SEYaDQRiEQnq6NCVw4"
  },
  {
    "placeId": "ChIJe219kIYXaDQRSxfVBOBkgaQ",
    "name": "TINA廚房-大溪店",
    "address": "335台灣桃园市大溪区瑞兴里瑞安路一段175巷55號",
    "category": "restaurant",
    "rating": 4.6,
    "reviewCount": 7410,
    "lat": 24.8875758,
    "lng": 121.28020459999999,
    "distanceMeters": 861,
    "distanceLabel": "860m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.8875758,121.28020459999999&destination_place_id=ChIJe219kIYXaDQRSxfVBOBkgaQ"
  },
  {
    "placeId": "ChIJu6ih3yMYaDQRD1tMK9wiPD0",
    "name": "乾麵居",
    "address": "335台灣桃園市大溪區民權東路7號",
    "category": "taiwanese_restaurant",
    "rating": 4,
    "reviewCount": 3327,
    "lat": 24.8835528,
    "lng": 121.28952,
    "distanceMeters": 202,
    "distanceLabel": "200m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.8835528,121.28952&destination_place_id=ChIJu6ih3yMYaDQRD1tMK9wiPD0"
  },
  {
    "placeId": "ChIJKyFr8yEYaDQRBl0Q5V97N2Y",
    "name": "賴媽媽傳統豆花 體育館本店",
    "address": "335台灣桃園市大溪區福仁里登龍路22號多目標體育館1樓",
    "category": "dessert_shop",
    "rating": 4.1,
    "reviewCount": 2359,
    "lat": 24.883544699999998,
    "lng": 121.2872067,
    "distanceMeters": 188,
    "distanceLabel": "190m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.883544699999998,121.2872067&destination_place_id=ChIJKyFr8yEYaDQRBl0Q5V97N2Y"
  },
  {
    "placeId": "ChIJUzGqYiEYaDQR1LT76BztB4A",
    "name": "陳師兄素肉圓",
    "address": "335台灣桃園市大溪區一心里慈湖路24之1號",
    "category": "vegetarian_restaurant",
    "rating": 4.4,
    "reviewCount": 2335,
    "lat": 24.883613,
    "lng": 121.28910699999999,
    "distanceMeters": 173,
    "distanceLabel": "170m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.883613,121.28910699999999&destination_place_id=ChIJUzGqYiEYaDQR1LT76BztB4A"
  },
  {
    "placeId": "ChIJVQoafpUZaDQRxDtVpQ352y8",
    "name": "大溪花市",
    "address": "335台灣桃園市大溪區瑞興里瑞安路一段474號",
    "category": "market",
    "rating": 4.5,
    "reviewCount": 2335,
    "lat": 24.8834317,
    "lng": 121.2796738,
    "distanceMeters": 880,
    "distanceLabel": "880m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.8834317,121.2796738&destination_place_id=ChIJVQoafpUZaDQRxDtVpQ352y8"
  },
  {
    "placeId": "ChIJNW-PBSEYaDQRdNsv21FxI-E",
    "name": "麥當勞-大溪慈湖餐廳－設有得來速",
    "address": "335台灣桃園市大溪區一心里慈湖路99號1樓",
    "category": "fast_food_restaurant",
    "rating": 3.8,
    "reviewCount": 1786,
    "lat": 24.881735,
    "lng": 121.28905300000001,
    "distanceMeters": 367,
    "distanceLabel": "370m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.881735,121.28905300000001&destination_place_id=ChIJNW-PBSEYaDQRdNsv21FxI-E"
  },
  {
    "placeId": "ChIJb7rCACIYaDQR3yvcEznYI3A",
    "name": "溪友緣風味料理餐廳",
    "address": "335台灣桃園市大溪區福仁里仁愛路9號",
    "category": "chinese_restaurant",
    "rating": 4.4,
    "reviewCount": 1654,
    "lat": 24.8846391,
    "lng": 121.28563240000001,
    "distanceMeters": 265,
    "distanceLabel": "270m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.8846391,121.28563240000001&destination_place_id=ChIJb7rCACIYaDQR3yvcEznYI3A"
  },
  {
    "placeId": "ChIJ1ZQR550ZaDQR7cNv3j-uEXg",
    "name": "文創咖美食館",
    "address": "335台灣桃園市大溪區興和里登龍路5之8號",
    "category": "restaurant",
    "rating": 4.8,
    "reviewCount": 1553,
    "lat": 24.882828099999998,
    "lng": 121.28620989999999,
    "distanceMeters": 312,
    "distanceLabel": "310m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.882828099999998,121.28620989999999&destination_place_id=ChIJ1ZQR550ZaDQR7cNv3j-uEXg"
  },
  {
    "placeId": "ChIJR01hKyIYaDQRQCD0hbGmyUA",
    "name": "游記百年油飯",
    "address": "335台灣桃園市大溪區福仁里民權路17號",
    "category": "taiwanese_restaurant",
    "rating": 3.8,
    "reviewCount": 1515,
    "lat": 24.884127799999998,
    "lng": 121.28802049999999,
    "distanceMeters": 94,
    "distanceLabel": "90m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.884127799999998,121.28802049999999&destination_place_id=ChIJR01hKyIYaDQRQCD0hbGmyUA"
  },
  {
    "placeId": "ChIJ9Xxo9hMZaDQRaPyz8G1-cgE",
    "name": "隱花園景觀咖啡餐廳",
    "address": "335台灣桃園市大溪區中央路41號",
    "category": "restaurant",
    "rating": 4.7,
    "reviewCount": 1494,
    "lat": 24.879512899999998,
    "lng": 121.28769030000001,
    "distanceMeters": 607,
    "distanceLabel": "610m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.879512899999998,121.28769030000001&destination_place_id=ChIJ9Xxo9hMZaDQRaPyz8G1-cgE"
  },
  {
    "placeId": "ChIJ7dUTVjQZaDQRxn9hBGDZyuw",
    "name": "隱灶腳百年老厝餐館",
    "address": "335台灣桃園市大溪區中央路36-1號",
    "category": "restaurant",
    "rating": 4.8,
    "reviewCount": 1137,
    "lat": 24.879335899999997,
    "lng": 121.2878686,
    "distanceMeters": 626,
    "distanceLabel": "630m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.879335899999997,121.2878686&destination_place_id=ChIJ7dUTVjQZaDQRxn9hBGDZyuw"
  },
  {
    "placeId": "ChIJK0jebiMZaDQRrjSwQP-Vi48",
    "name": "春草舒願(蔬食料理)",
    "address": "335台灣桃園市大溪區月眉里月眉路52號",
    "category": "vegan_restaurant",
    "rating": 4.8,
    "reviewCount": 1024,
    "lat": 24.8863125,
    "lng": 121.2886248,
    "distanceMeters": 156,
    "distanceLabel": "160m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.8863125,121.2886248&destination_place_id=ChIJK0jebiMZaDQRrjSwQP-Vi48"
  },
  {
    "placeId": "ChIJ_R5-JScYaDQRIJgn9T-ysM0",
    "name": "大溪夜市",
    "address": "335台灣桃園市大溪區文化路",
    "category": "market",
    "rating": 4.1,
    "reviewCount": 1021,
    "lat": 24.8784094,
    "lng": 121.290891,
    "distanceMeters": 775,
    "distanceLabel": "780m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.8784094,121.290891&destination_place_id=ChIJ_R5-JScYaDQRIJgn9T-ysM0"
  },
  {
    "placeId": "ChIJCVtR0CEYaDQRf0TIcrLloeY",
    "name": "藝享茶",
    "address": "335台灣桃園市大溪區興和里登龍路4號",
    "category": "tea_house",
    "rating": 4.8,
    "reviewCount": 890,
    "lat": 24.8823747,
    "lng": 121.28610850000001,
    "distanceMeters": 358,
    "distanceLabel": "360m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.8823747,121.28610850000001&destination_place_id=ChIJCVtR0CEYaDQRf0TIcrLloeY"
  },
  {
    "placeId": "ChIJ94ldaiIYaDQRpmoc1mXUTXU",
    "name": "大溪拿破崙派",
    "address": "335台灣桃園市大溪區福仁里和平路94號",
    "category": "bakery",
    "rating": 4.4,
    "reviewCount": 759,
    "lat": 24.885683,
    "lng": 121.286838,
    "distanceMeters": 163,
    "distanceLabel": "160m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.885683,121.286838&destination_place_id=ChIJ94ldaiIYaDQRpmoc1mXUTXU"
  },
  {
    "placeId": "ChIJh35SqR4YaDQRyZ0M4U8Q3WE",
    "name": "基隆全家福海鮮餐廳 大溪分店",
    "address": "335台灣桃園市大溪區瑞興里瑞安路一段308號",
    "category": "seafood_restaurant",
    "rating": 4,
    "reviewCount": 734,
    "lat": 24.885059,
    "lng": 121.2801686,
    "distanceMeters": 814,
    "distanceLabel": "810m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.885059,121.2801686&destination_place_id=ChIJh35SqR4YaDQRyZ0M4U8Q3WE"
  },
  {
    "placeId": "ChIJpWj5jiYYaDQRh6kbeGlR_UE",
    "name": "全聯福利中心 大溪文化店",
    "address": "335台灣桃園市大溪區田心里文化路67號",
    "category": "supermarket",
    "rating": 4.1,
    "reviewCount": 728,
    "lat": 24.8817333,
    "lng": 121.29356589999999,
    "distanceMeters": 646,
    "distanceLabel": "650m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.8817333,121.29356589999999&destination_place_id=ChIJpWj5jiYYaDQRh6kbeGlR_UE"
  },
  {
    "placeId": "ChIJGZNuNCIYaDQRpof7Fmz5TQA",
    "name": "蔡記花生糖（原老店）",
    "address": "335台灣桃園市大溪區福仁里和平路57號",
    "category": "dessert_restaurant",
    "rating": 4.3,
    "reviewCount": 667,
    "lat": 24.8850817,
    "lng": 121.28751479999998,
    "distanceMeters": 74,
    "distanceLabel": "70m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.8850817,121.28751479999998&destination_place_id=ChIJGZNuNCIYaDQRpof7Fmz5TQA"
  },
  {
    "placeId": "ChIJS1fX0yEYaDQR9HtJiSxcYHA",
    "name": "韓鄉石頭火鍋（訂於2025年9月27號，星期六開始營業！ 歡迎舊雨新知、再度光臨！）",
    "address": "335台灣桃園市大溪區興和里中山路46-1號",
    "category": "chinese_restaurant",
    "rating": 4.3,
    "reviewCount": 666,
    "lat": 24.8820266,
    "lng": 121.28602759999998,
    "distanceMeters": 394,
    "distanceLabel": "390m",
    "mapsUrl": "https://www.google.com/maps/dir/?api=1&destination=24.8820266,121.28602759999998&destination_place_id=ChIJS1fX0yEYaDQR9HtJiSxcYHA"
  }
];
